# Generated by Django 4.1.2 on 2022-10-12 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('azbooks', '0002_access_level_accounting_type_chart_of_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('accounting_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Sale', 'Sale'), ('Expense', 'Expense')], max_length=100)),
                ('is_bank_account', models.BooleanField(default=False)),
                ('is_sale_tax_account', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'chart of accounts',
            },
        ),
        migrations.CreateModel(
            name='Historicalaccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('accounting_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Sale', 'Sale'), ('Expense', 'Expense')], max_length=100)),
                ('is_bank_account', models.BooleanField(default=False)),
                ('is_sale_tax_account', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical chart of accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='chart_of_accounts',
            name='accounting_type',
        ),
        migrations.RemoveField(
            model_name='chart_of_accounts',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalaccess_level',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalaccounting_type',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchart_of_accounts',
            name='accounting_type',
        ),
        migrations.RemoveField(
            model_name='historicalchart_of_accounts',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchart_of_accounts',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='historicalcountry',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical country', 'verbose_name_plural': 'historical countries'},
        ),
        migrations.AlterModelOptions(
            name='historicalcurrency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical currency', 'verbose_name_plural': 'historical currencies'},
        ),
        migrations.AlterModelOptions(
            name='historicaluser_organization_access',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user organization access', 'verbose_name_plural': 'historical user organization access'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='user_organization_access',
            options={'verbose_name': 'user organization access', 'verbose_name_plural': 'user organization access'},
        ),
        migrations.RemoveField(
            model_name='historicaluser_organization_access',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='user_organization_access',
            name='access_level',
        ),
        migrations.DeleteModel(
            name='access_level',
        ),
        migrations.DeleteModel(
            name='accounting_type',
        ),
        migrations.DeleteModel(
            name='Historicalaccess_level',
        ),
        migrations.DeleteModel(
            name='Historicalaccounting_type',
        ),
        migrations.DeleteModel(
            name='Historicalchart_of_accounts',
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='azbooks.organization'),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azbooks.organization'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_detail',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='azbooks.account'),
        ),
        migrations.AlterField(
            model_name='transaction_detail',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azbooks.account'),
        ),
        migrations.DeleteModel(
            name='chart_of_accounts',
        ),
    ]
