# Generated by Django 4.1.2 on 2022-10-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azbooks', '0003_account_historicalaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcountry',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='historicalcountry',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcurrency',
            name='history_user',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accounting_type',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='historicalaccount',
            old_name='accounting_type',
            new_name='account_type',
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='country',
            field=models.CharField(blank=True, choices=[('Aruba', 'Aruba'), ('Afghanistan', 'Afghanistan'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Åland Islands', 'Åland Islands'), ('Albania', 'Albania'), ('Andorra', 'Andorra'), ('United Arab Emirates', 'United Arab Emirates'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('American Samoa', 'American Samoa'), ('Antarctica', 'Antarctica'), ('French Southern Territories', 'French Southern Territories'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Burundi', 'Burundi'), ('Belgium', 'Belgium'), ('Benin', 'Benin'), ('Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'), ('Burkina Faso', 'Burkina Faso'), ('Bangladesh', 'Bangladesh'), ('Bulgaria', 'Bulgaria'), ('Bahrain', 'Bahrain'), ('Bahamas', 'Bahamas'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Belarus', 'Belarus'), ('Belize', 'Belize'), ('Bermuda', 'Bermuda'), ('Bolivia, Plurinational State of', 'Bolivia, Plurinational State of'), ('Brazil', 'Brazil'), ('Barbados', 'Barbados'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bhutan', 'Bhutan'), ('Bouvet Island', 'Bouvet Island'), ('Botswana', 'Botswana'), ('Central African Republic', 'Central African Republic'), ('Canada', 'Canada'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Switzerland', 'Switzerland'), ('Chile', 'Chile'), ('China', 'China'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Cameroon', 'Cameroon'), ('Congo, The Democratic Republic of the', 'Congo, The Democratic Republic of the'), ('Congo', 'Congo'), ('Cook Islands', 'Cook Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Cabo Verde', 'Cabo Verde'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Curaçao', 'Curaçao'), ('Christmas Island', 'Christmas Island'), ('Cayman Islands', 'Cayman Islands'), ('Cyprus', 'Cyprus'), ('Czechia', 'Czechia'), ('Germany', 'Germany'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Denmark', 'Denmark'), ('Dominican Republic', 'Dominican Republic'), ('Algeria', 'Algeria'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('Eritrea', 'Eritrea'), ('Western Sahara', 'Western Sahara'), ('Spain', 'Spain'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Finland', 'Finland'), ('Fiji', 'Fiji'), ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'), ('France', 'France'), ('Faroe Islands', 'Faroe Islands'), ('Micronesia, Federated States of', 'Micronesia, Federated States of'), ('Gabon', 'Gabon'), ('United Kingdom', 'United Kingdom'), ('Georgia', 'Georgia'), ('Guernsey', 'Guernsey'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Guinea', 'Guinea'), ('Guadeloupe', 'Guadeloupe'), ('Gambia', 'Gambia'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Greenland', 'Greenland'), ('Guatemala', 'Guatemala'), ('French Guiana', 'French Guiana'), ('Guam', 'Guam'), ('Guyana', 'Guyana'), ('Hong Kong', 'Hong Kong'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Honduras', 'Honduras'), ('Croatia', 'Croatia'), ('Haiti', 'Haiti'), ('Hungary', 'Hungary'), ('Indonesia', 'Indonesia'), ('Isle of Man', 'Isle of Man'), ('India', 'India'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Ireland', 'Ireland'), ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'), ('Iraq', 'Iraq'), ('Iceland', 'Iceland'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Japan', 'Japan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Cambodia', 'Cambodia'), ('Kiribati', 'Kiribati'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Korea, Republic of', 'Korea, Republic of'), ('Kuwait', 'Kuwait'), ("Lao People's Democratic Republic", "Lao People's Democratic Republic"), ('Lebanon', 'Lebanon'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Saint Lucia', 'Saint Lucia'), ('Liechtenstein', 'Liechtenstein'), ('Sri Lanka', 'Sri Lanka'), ('Lesotho', 'Lesotho'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Latvia', 'Latvia'), ('Macao', 'Macao'), ('Saint Martin (French part)', 'Saint Martin (French part)'), ('Morocco', 'Morocco'), ('Monaco', 'Monaco'), ('Moldova, Republic of', 'Moldova, Republic of'), ('Madagascar', 'Madagascar'), ('Maldives', 'Maldives'), ('Mexico', 'Mexico'), ('Marshall Islands', 'Marshall Islands'), ('North Macedonia', 'North Macedonia'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Myanmar', 'Myanmar'), ('Montenegro', 'Montenegro'), ('Mongolia', 'Mongolia'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Mozambique', 'Mozambique'), ('Mauritania', 'Mauritania'), ('Montserrat', 'Montserrat'), ('Martinique', 'Martinique'), ('Mauritius', 'Mauritius'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Mayotte', 'Mayotte'), ('Namibia', 'Namibia'), ('New Caledonia', 'New Caledonia'), ('Niger', 'Niger'), ('Norfolk Island', 'Norfolk Island'), ('Nigeria', 'Nigeria'), ('Nicaragua', 'Nicaragua'), ('Niue', 'Niue'), ('Netherlands', 'Netherlands'), ('Norway', 'Norway'), ('Nepal', 'Nepal'), ('Nauru', 'Nauru'), ('New Zealand', 'New Zealand'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Panama', 'Panama'), ('Pitcairn', 'Pitcairn'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Palau', 'Palau'), ('Papua New Guinea', 'Papua New Guinea'), ('Poland', 'Poland'), ('Puerto Rico', 'Puerto Rico'), ("Korea, Democratic People's Republic of", "Korea, Democratic People's Republic of"), ('Portugal', 'Portugal'), ('Paraguay', 'Paraguay'), ('Palestine, State of', 'Palestine, State of'), ('French Polynesia', 'French Polynesia'), ('Qatar', 'Qatar'), ('Réunion', 'Réunion'), ('Romania', 'Romania'), ('Russian Federation', 'Russian Federation'), ('Rwanda', 'Rwanda'), ('Saudi Arabia', 'Saudi Arabia'), ('Sudan', 'Sudan'), ('Senegal', 'Senegal'), ('Singapore', 'Singapore'), ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), ('Solomon Islands', 'Solomon Islands'), ('Sierra Leone', 'Sierra Leone'), ('El Salvador', 'El Salvador'), ('San Marino', 'San Marino'), ('Somalia', 'Somalia'), ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Serbia', 'Serbia'), ('South Sudan', 'South Sudan'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Suriname', 'Suriname'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Sweden', 'Sweden'), ('Eswatini', 'Eswatini'), ('Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)'), ('Seychelles', 'Seychelles'), ('Syrian Arab Republic', 'Syrian Arab Republic'), ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Chad', 'Chad'), ('Togo', 'Togo'), ('Thailand', 'Thailand'), ('Tajikistan', 'Tajikistan'), ('Tokelau', 'Tokelau'), ('Turkmenistan', 'Turkmenistan'), ('Timor-Leste', 'Timor-Leste'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Tuvalu', 'Tuvalu'), ('Taiwan, Province of China', 'Taiwan, Province of China'), ('Tanzania, United Republic of', 'Tanzania, United Republic of'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Uruguay', 'Uruguay'), ('United States', 'United States'), ('Uzbekistan', 'Uzbekistan'), ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of'), ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'), ('Viet Nam', 'Viet Nam'), ('Vanuatu', 'Vanuatu'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Samoa', 'Samoa'), ('Yemen', 'Yemen'), ('South Africa', 'South Africa'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAE Dirham', 'UAE Dirham'), ('Afghani', 'Afghani'), ('Lek', 'Lek'), ('Armenian Dram', 'Armenian Dram'), ('Netherlands Antillean Guilder', 'Netherlands Antillean Guilder'), ('Kwanza', 'Kwanza'), ('Argentine Peso', 'Argentine Peso'), ('Australian Dollar', 'Australian Dollar'), ('Aruban Florin', 'Aruban Florin'), ('Azerbaijanian Manat', 'Azerbaijanian Manat'), ('Convertible Mark', 'Convertible Mark'), ('Barbados Dollar', 'Barbados Dollar'), ('Taka', 'Taka'), ('Bulgarian Lev', 'Bulgarian Lev'), ('Bahraini Dinar', 'Bahraini Dinar'), ('Burundi Franc', 'Burundi Franc'), ('Bermudian Dollar', 'Bermudian Dollar'), ('Brunei Dollar', 'Brunei Dollar'), ('Boliviano', 'Boliviano'), ('Brazilian Real', 'Brazilian Real'), ('Bahamian Dollar', 'Bahamian Dollar'), ('Ngultrum', 'Ngultrum'), ('Pula', 'Pula'), ('Belarusian Ruble', 'Belarusian Ruble'), ('Belize Dollar', 'Belize Dollar'), ('Canadian Dollar', 'Canadian Dollar'), ('Congolese Franc', 'Congolese Franc'), ('Swiss Franc', 'Swiss Franc'), ('Chilean Peso', 'Chilean Peso'), ('Yuan Renminbi', 'Yuan Renminbi'), ('Colombian Peso', 'Colombian Peso'), ('Costa Rican Colon', 'Costa Rican Colon'), ('Peso Convertible', 'Peso Convertible'), ('Cuban Peso', 'Cuban Peso'), ('Cabo Verde Escudo', 'Cabo Verde Escudo'), ('Czech Koruna', 'Czech Koruna'), ('Djibouti Franc', 'Djibouti Franc'), ('Danish Krone', 'Danish Krone'), ('Dominican Peso', 'Dominican Peso'), ('Algerian Dinar', 'Algerian Dinar'), ('Egyptian Pound', 'Egyptian Pound'), ('Nakfa', 'Nakfa'), ('Ethiopian Birr', 'Ethiopian Birr'), ('Euro', 'Euro'), ('Fiji Dollar', 'Fiji Dollar'), ('Falkland Islands Pound', 'Falkland Islands Pound'), ('Pound Sterling', 'Pound Sterling'), ('Lari', 'Lari'), ('Ghana Cedi', 'Ghana Cedi'), ('Gibraltar Pound', 'Gibraltar Pound'), ('Dalasi', 'Dalasi'), ('Guinea Franc', 'Guinea Franc'), ('Quetzal', 'Quetzal'), ('Guyana Dollar', 'Guyana Dollar'), ('Hong Kong Dollar', 'Hong Kong Dollar'), ('Lempira', 'Lempira'), ('Kuna', 'Kuna'), ('Gourde', 'Gourde'), ('Forint', 'Forint'), ('Rupiah', 'Rupiah'), ('New Israeli Sheqel', 'New Israeli Sheqel'), ('Indian Rupee', 'Indian Rupee'), ('Iraqi Dinar', 'Iraqi Dinar'), ('Iranian Rial', 'Iranian Rial'), ('Iceland Krona', 'Iceland Krona'), ('Jamaican Dollar', 'Jamaican Dollar'), ('Jordanian Dinar', 'Jordanian Dinar'), ('Yen', 'Yen'), ('Kenyan Shilling', 'Kenyan Shilling'), ('Som', 'Som'), ('Riel', 'Riel'), ('Comoro Franc', 'Comoro Franc'), ('North Korean Won', 'North Korean Won'), ('Won', 'Won'), ('Kuwaiti Dinar', 'Kuwaiti Dinar'), ('Cayman Islands Dollar', 'Cayman Islands Dollar'), ('Tenge', 'Tenge'), ('Kip', 'Kip'), ('Lebanese Pound', 'Lebanese Pound'), ('Sri Lanka Rupee', 'Sri Lanka Rupee'), ('Liberian Dollar', 'Liberian Dollar'), ('Loti', 'Loti'), ('Libyan Dinar', 'Libyan Dinar'), ('Moroccan Dirham', 'Moroccan Dirham'), ('Moldovan Leu', 'Moldovan Leu'), ('Malagasy Ariary', 'Malagasy Ariary'), ('Denar', 'Denar'), ('Kyat', 'Kyat'), ('Tugrik', 'Tugrik'), ('Pataca', 'Pataca'), ('Ouguiya', 'Ouguiya'), ('Mauritius Rupee', 'Mauritius Rupee'), ('Rufiyaa', 'Rufiyaa'), ('Malawi Kwacha', 'Malawi Kwacha'), ('Mexican Peso', 'Mexican Peso'), ('Malaysian Ringgit', 'Malaysian Ringgit'), ('Mozambique Metical', 'Mozambique Metical'), ('Namibia Dollar', 'Namibia Dollar'), ('Naira', 'Naira'), ('Cordoba Oro', 'Cordoba Oro'), ('Norwegian Krone', 'Norwegian Krone'), ('Nepalese Rupee', 'Nepalese Rupee'), ('New Zealand Dollar', 'New Zealand Dollar'), ('Rial Omani', 'Rial Omani'), ('Balboa', 'Balboa'), ('Sol', 'Sol'), ('Kina', 'Kina'), ('Philippine Peso', 'Philippine Peso'), ('Pakistan Rupee', 'Pakistan Rupee'), ('Zloty', 'Zloty'), ('Guarani', 'Guarani'), ('Qatari Rial', 'Qatari Rial'), ('Romanian Leu', 'Romanian Leu'), ('Serbian Dinar', 'Serbian Dinar'), ('Russian Ruble', 'Russian Ruble'), ('Rwanda Franc', 'Rwanda Franc'), ('Saudi Riyal', 'Saudi Riyal'), ('Solomon Islands Dollar', 'Solomon Islands Dollar'), ('Seychelles Rupee', 'Seychelles Rupee'), ('Sudanese Pound', 'Sudanese Pound'), ('Swedish Krona', 'Swedish Krona'), ('Singapore Dollar', 'Singapore Dollar'), ('Saint Helena Pound', 'Saint Helena Pound'), ('Leone', 'Leone'), ('Somali Shilling', 'Somali Shilling'), ('Surinam Dollar', 'Surinam Dollar'), ('South Sudanese Pound', 'South Sudanese Pound'), ('Dobra', 'Dobra'), ('El Salvador Colon', 'El Salvador Colon'), ('Syrian Pound', 'Syrian Pound'), ('Lilangeni', 'Lilangeni'), ('Baht', 'Baht'), ('Somoni', 'Somoni'), ('Turkmenistan New Manat', 'Turkmenistan New Manat'), ('Tunisian Dinar', 'Tunisian Dinar'), ('Pa’anga', 'Pa’anga'), ('Turkish Lira', 'Turkish Lira'), ('Trinidad and Tobago Dollar', 'Trinidad and Tobago Dollar'), ('New Taiwan Dollar', 'New Taiwan Dollar'), ('Tanzanian Shilling', 'Tanzanian Shilling'), ('Hryvnia', 'Hryvnia'), ('Uganda Shilling', 'Uganda Shilling'), ('US Dollar', 'US Dollar'), ('Peso Uruguayo', 'Peso Uruguayo'), ('Uzbekistan Sum', 'Uzbekistan Sum'), ('Bolívar', 'Bolívar'), ('Dong', 'Dong'), ('Vatu', 'Vatu'), ('Tala', 'Tala'), ('CFA Franc BEAC', 'CFA Franc BEAC'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Bond Markets Unit European Composite Unit (EURCO)', 'Bond Markets Unit European Composite Unit (EURCO)'), ('Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)'), ('Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)'), ('Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)'), ('East Caribbean Dollar', 'East Caribbean Dollar'), ('SDR (Special Drawing Right)', 'SDR (Special Drawing Right)'), ('CFA Franc BCEAO', 'CFA Franc BCEAO'), ('Palladium', 'Palladium'), ('CFP Franc', 'CFP Franc'), ('Platinum', 'Platinum'), ('Sucre', 'Sucre'), ('Codes specifically reserved for testing purposes', 'Codes specifically reserved for testing purposes'), ('ADB Unit of Account', 'ADB Unit of Account'), ('The codes assigned for transactions where no currency is involved', 'The codes assigned for transactions where no currency is involved'), ('Yemeni Rial', 'Yemeni Rial'), ('Rand', 'Rand'), ('Zambian Kwacha', 'Zambian Kwacha'), ('Zimbabwe Dollar', 'Zimbabwe Dollar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparty',
            name='is_bank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparty',
            name='is_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparty',
            name='is_employee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparty',
            name='is_supplier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparty',
            name='legal_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_header',
            name='date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_header',
            name='folio_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_header',
            name='memo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_header',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_header',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, choices=[('Aruba', 'Aruba'), ('Afghanistan', 'Afghanistan'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Åland Islands', 'Åland Islands'), ('Albania', 'Albania'), ('Andorra', 'Andorra'), ('United Arab Emirates', 'United Arab Emirates'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('American Samoa', 'American Samoa'), ('Antarctica', 'Antarctica'), ('French Southern Territories', 'French Southern Territories'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Burundi', 'Burundi'), ('Belgium', 'Belgium'), ('Benin', 'Benin'), ('Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'), ('Burkina Faso', 'Burkina Faso'), ('Bangladesh', 'Bangladesh'), ('Bulgaria', 'Bulgaria'), ('Bahrain', 'Bahrain'), ('Bahamas', 'Bahamas'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Belarus', 'Belarus'), ('Belize', 'Belize'), ('Bermuda', 'Bermuda'), ('Bolivia, Plurinational State of', 'Bolivia, Plurinational State of'), ('Brazil', 'Brazil'), ('Barbados', 'Barbados'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bhutan', 'Bhutan'), ('Bouvet Island', 'Bouvet Island'), ('Botswana', 'Botswana'), ('Central African Republic', 'Central African Republic'), ('Canada', 'Canada'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Switzerland', 'Switzerland'), ('Chile', 'Chile'), ('China', 'China'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Cameroon', 'Cameroon'), ('Congo, The Democratic Republic of the', 'Congo, The Democratic Republic of the'), ('Congo', 'Congo'), ('Cook Islands', 'Cook Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Cabo Verde', 'Cabo Verde'), ('Costa Rica', 'Costa Rica'), ('Cuba', 'Cuba'), ('Curaçao', 'Curaçao'), ('Christmas Island', 'Christmas Island'), ('Cayman Islands', 'Cayman Islands'), ('Cyprus', 'Cyprus'), ('Czechia', 'Czechia'), ('Germany', 'Germany'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Denmark', 'Denmark'), ('Dominican Republic', 'Dominican Republic'), ('Algeria', 'Algeria'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('Eritrea', 'Eritrea'), ('Western Sahara', 'Western Sahara'), ('Spain', 'Spain'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Finland', 'Finland'), ('Fiji', 'Fiji'), ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'), ('France', 'France'), ('Faroe Islands', 'Faroe Islands'), ('Micronesia, Federated States of', 'Micronesia, Federated States of'), ('Gabon', 'Gabon'), ('United Kingdom', 'United Kingdom'), ('Georgia', 'Georgia'), ('Guernsey', 'Guernsey'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Guinea', 'Guinea'), ('Guadeloupe', 'Guadeloupe'), ('Gambia', 'Gambia'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Greenland', 'Greenland'), ('Guatemala', 'Guatemala'), ('French Guiana', 'French Guiana'), ('Guam', 'Guam'), ('Guyana', 'Guyana'), ('Hong Kong', 'Hong Kong'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Honduras', 'Honduras'), ('Croatia', 'Croatia'), ('Haiti', 'Haiti'), ('Hungary', 'Hungary'), ('Indonesia', 'Indonesia'), ('Isle of Man', 'Isle of Man'), ('India', 'India'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Ireland', 'Ireland'), ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'), ('Iraq', 'Iraq'), ('Iceland', 'Iceland'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Japan', 'Japan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Cambodia', 'Cambodia'), ('Kiribati', 'Kiribati'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Korea, Republic of', 'Korea, Republic of'), ('Kuwait', 'Kuwait'), ("Lao People's Democratic Republic", "Lao People's Democratic Republic"), ('Lebanon', 'Lebanon'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Saint Lucia', 'Saint Lucia'), ('Liechtenstein', 'Liechtenstein'), ('Sri Lanka', 'Sri Lanka'), ('Lesotho', 'Lesotho'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Latvia', 'Latvia'), ('Macao', 'Macao'), ('Saint Martin (French part)', 'Saint Martin (French part)'), ('Morocco', 'Morocco'), ('Monaco', 'Monaco'), ('Moldova, Republic of', 'Moldova, Republic of'), ('Madagascar', 'Madagascar'), ('Maldives', 'Maldives'), ('Mexico', 'Mexico'), ('Marshall Islands', 'Marshall Islands'), ('North Macedonia', 'North Macedonia'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Myanmar', 'Myanmar'), ('Montenegro', 'Montenegro'), ('Mongolia', 'Mongolia'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Mozambique', 'Mozambique'), ('Mauritania', 'Mauritania'), ('Montserrat', 'Montserrat'), ('Martinique', 'Martinique'), ('Mauritius', 'Mauritius'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Mayotte', 'Mayotte'), ('Namibia', 'Namibia'), ('New Caledonia', 'New Caledonia'), ('Niger', 'Niger'), ('Norfolk Island', 'Norfolk Island'), ('Nigeria', 'Nigeria'), ('Nicaragua', 'Nicaragua'), ('Niue', 'Niue'), ('Netherlands', 'Netherlands'), ('Norway', 'Norway'), ('Nepal', 'Nepal'), ('Nauru', 'Nauru'), ('New Zealand', 'New Zealand'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Panama', 'Panama'), ('Pitcairn', 'Pitcairn'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Palau', 'Palau'), ('Papua New Guinea', 'Papua New Guinea'), ('Poland', 'Poland'), ('Puerto Rico', 'Puerto Rico'), ("Korea, Democratic People's Republic of", "Korea, Democratic People's Republic of"), ('Portugal', 'Portugal'), ('Paraguay', 'Paraguay'), ('Palestine, State of', 'Palestine, State of'), ('French Polynesia', 'French Polynesia'), ('Qatar', 'Qatar'), ('Réunion', 'Réunion'), ('Romania', 'Romania'), ('Russian Federation', 'Russian Federation'), ('Rwanda', 'Rwanda'), ('Saudi Arabia', 'Saudi Arabia'), ('Sudan', 'Sudan'), ('Senegal', 'Senegal'), ('Singapore', 'Singapore'), ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), ('Solomon Islands', 'Solomon Islands'), ('Sierra Leone', 'Sierra Leone'), ('El Salvador', 'El Salvador'), ('San Marino', 'San Marino'), ('Somalia', 'Somalia'), ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Serbia', 'Serbia'), ('South Sudan', 'South Sudan'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Suriname', 'Suriname'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Sweden', 'Sweden'), ('Eswatini', 'Eswatini'), ('Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)'), ('Seychelles', 'Seychelles'), ('Syrian Arab Republic', 'Syrian Arab Republic'), ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Chad', 'Chad'), ('Togo', 'Togo'), ('Thailand', 'Thailand'), ('Tajikistan', 'Tajikistan'), ('Tokelau', 'Tokelau'), ('Turkmenistan', 'Turkmenistan'), ('Timor-Leste', 'Timor-Leste'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Tuvalu', 'Tuvalu'), ('Taiwan, Province of China', 'Taiwan, Province of China'), ('Tanzania, United Republic of', 'Tanzania, United Republic of'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Uruguay', 'Uruguay'), ('United States', 'United States'), ('Uzbekistan', 'Uzbekistan'), ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of'), ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'), ('Viet Nam', 'Viet Nam'), ('Vanuatu', 'Vanuatu'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Samoa', 'Samoa'), ('Yemen', 'Yemen'), ('South Africa', 'South Africa'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAE Dirham', 'UAE Dirham'), ('Afghani', 'Afghani'), ('Lek', 'Lek'), ('Armenian Dram', 'Armenian Dram'), ('Netherlands Antillean Guilder', 'Netherlands Antillean Guilder'), ('Kwanza', 'Kwanza'), ('Argentine Peso', 'Argentine Peso'), ('Australian Dollar', 'Australian Dollar'), ('Aruban Florin', 'Aruban Florin'), ('Azerbaijanian Manat', 'Azerbaijanian Manat'), ('Convertible Mark', 'Convertible Mark'), ('Barbados Dollar', 'Barbados Dollar'), ('Taka', 'Taka'), ('Bulgarian Lev', 'Bulgarian Lev'), ('Bahraini Dinar', 'Bahraini Dinar'), ('Burundi Franc', 'Burundi Franc'), ('Bermudian Dollar', 'Bermudian Dollar'), ('Brunei Dollar', 'Brunei Dollar'), ('Boliviano', 'Boliviano'), ('Brazilian Real', 'Brazilian Real'), ('Bahamian Dollar', 'Bahamian Dollar'), ('Ngultrum', 'Ngultrum'), ('Pula', 'Pula'), ('Belarusian Ruble', 'Belarusian Ruble'), ('Belize Dollar', 'Belize Dollar'), ('Canadian Dollar', 'Canadian Dollar'), ('Congolese Franc', 'Congolese Franc'), ('Swiss Franc', 'Swiss Franc'), ('Chilean Peso', 'Chilean Peso'), ('Yuan Renminbi', 'Yuan Renminbi'), ('Colombian Peso', 'Colombian Peso'), ('Costa Rican Colon', 'Costa Rican Colon'), ('Peso Convertible', 'Peso Convertible'), ('Cuban Peso', 'Cuban Peso'), ('Cabo Verde Escudo', 'Cabo Verde Escudo'), ('Czech Koruna', 'Czech Koruna'), ('Djibouti Franc', 'Djibouti Franc'), ('Danish Krone', 'Danish Krone'), ('Dominican Peso', 'Dominican Peso'), ('Algerian Dinar', 'Algerian Dinar'), ('Egyptian Pound', 'Egyptian Pound'), ('Nakfa', 'Nakfa'), ('Ethiopian Birr', 'Ethiopian Birr'), ('Euro', 'Euro'), ('Fiji Dollar', 'Fiji Dollar'), ('Falkland Islands Pound', 'Falkland Islands Pound'), ('Pound Sterling', 'Pound Sterling'), ('Lari', 'Lari'), ('Ghana Cedi', 'Ghana Cedi'), ('Gibraltar Pound', 'Gibraltar Pound'), ('Dalasi', 'Dalasi'), ('Guinea Franc', 'Guinea Franc'), ('Quetzal', 'Quetzal'), ('Guyana Dollar', 'Guyana Dollar'), ('Hong Kong Dollar', 'Hong Kong Dollar'), ('Lempira', 'Lempira'), ('Kuna', 'Kuna'), ('Gourde', 'Gourde'), ('Forint', 'Forint'), ('Rupiah', 'Rupiah'), ('New Israeli Sheqel', 'New Israeli Sheqel'), ('Indian Rupee', 'Indian Rupee'), ('Iraqi Dinar', 'Iraqi Dinar'), ('Iranian Rial', 'Iranian Rial'), ('Iceland Krona', 'Iceland Krona'), ('Jamaican Dollar', 'Jamaican Dollar'), ('Jordanian Dinar', 'Jordanian Dinar'), ('Yen', 'Yen'), ('Kenyan Shilling', 'Kenyan Shilling'), ('Som', 'Som'), ('Riel', 'Riel'), ('Comoro Franc', 'Comoro Franc'), ('North Korean Won', 'North Korean Won'), ('Won', 'Won'), ('Kuwaiti Dinar', 'Kuwaiti Dinar'), ('Cayman Islands Dollar', 'Cayman Islands Dollar'), ('Tenge', 'Tenge'), ('Kip', 'Kip'), ('Lebanese Pound', 'Lebanese Pound'), ('Sri Lanka Rupee', 'Sri Lanka Rupee'), ('Liberian Dollar', 'Liberian Dollar'), ('Loti', 'Loti'), ('Libyan Dinar', 'Libyan Dinar'), ('Moroccan Dirham', 'Moroccan Dirham'), ('Moldovan Leu', 'Moldovan Leu'), ('Malagasy Ariary', 'Malagasy Ariary'), ('Denar', 'Denar'), ('Kyat', 'Kyat'), ('Tugrik', 'Tugrik'), ('Pataca', 'Pataca'), ('Ouguiya', 'Ouguiya'), ('Mauritius Rupee', 'Mauritius Rupee'), ('Rufiyaa', 'Rufiyaa'), ('Malawi Kwacha', 'Malawi Kwacha'), ('Mexican Peso', 'Mexican Peso'), ('Malaysian Ringgit', 'Malaysian Ringgit'), ('Mozambique Metical', 'Mozambique Metical'), ('Namibia Dollar', 'Namibia Dollar'), ('Naira', 'Naira'), ('Cordoba Oro', 'Cordoba Oro'), ('Norwegian Krone', 'Norwegian Krone'), ('Nepalese Rupee', 'Nepalese Rupee'), ('New Zealand Dollar', 'New Zealand Dollar'), ('Rial Omani', 'Rial Omani'), ('Balboa', 'Balboa'), ('Sol', 'Sol'), ('Kina', 'Kina'), ('Philippine Peso', 'Philippine Peso'), ('Pakistan Rupee', 'Pakistan Rupee'), ('Zloty', 'Zloty'), ('Guarani', 'Guarani'), ('Qatari Rial', 'Qatari Rial'), ('Romanian Leu', 'Romanian Leu'), ('Serbian Dinar', 'Serbian Dinar'), ('Russian Ruble', 'Russian Ruble'), ('Rwanda Franc', 'Rwanda Franc'), ('Saudi Riyal', 'Saudi Riyal'), ('Solomon Islands Dollar', 'Solomon Islands Dollar'), ('Seychelles Rupee', 'Seychelles Rupee'), ('Sudanese Pound', 'Sudanese Pound'), ('Swedish Krona', 'Swedish Krona'), ('Singapore Dollar', 'Singapore Dollar'), ('Saint Helena Pound', 'Saint Helena Pound'), ('Leone', 'Leone'), ('Somali Shilling', 'Somali Shilling'), ('Surinam Dollar', 'Surinam Dollar'), ('South Sudanese Pound', 'South Sudanese Pound'), ('Dobra', 'Dobra'), ('El Salvador Colon', 'El Salvador Colon'), ('Syrian Pound', 'Syrian Pound'), ('Lilangeni', 'Lilangeni'), ('Baht', 'Baht'), ('Somoni', 'Somoni'), ('Turkmenistan New Manat', 'Turkmenistan New Manat'), ('Tunisian Dinar', 'Tunisian Dinar'), ('Pa’anga', 'Pa’anga'), ('Turkish Lira', 'Turkish Lira'), ('Trinidad and Tobago Dollar', 'Trinidad and Tobago Dollar'), ('New Taiwan Dollar', 'New Taiwan Dollar'), ('Tanzanian Shilling', 'Tanzanian Shilling'), ('Hryvnia', 'Hryvnia'), ('Uganda Shilling', 'Uganda Shilling'), ('US Dollar', 'US Dollar'), ('Peso Uruguayo', 'Peso Uruguayo'), ('Uzbekistan Sum', 'Uzbekistan Sum'), ('Bolívar', 'Bolívar'), ('Dong', 'Dong'), ('Vatu', 'Vatu'), ('Tala', 'Tala'), ('CFA Franc BEAC', 'CFA Franc BEAC'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Bond Markets Unit European Composite Unit (EURCO)', 'Bond Markets Unit European Composite Unit (EURCO)'), ('Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)'), ('Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)'), ('Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)'), ('East Caribbean Dollar', 'East Caribbean Dollar'), ('SDR (Special Drawing Right)', 'SDR (Special Drawing Right)'), ('CFA Franc BCEAO', 'CFA Franc BCEAO'), ('Palladium', 'Palladium'), ('CFP Franc', 'CFP Franc'), ('Platinum', 'Platinum'), ('Sucre', 'Sucre'), ('Codes specifically reserved for testing purposes', 'Codes specifically reserved for testing purposes'), ('ADB Unit of Account', 'ADB Unit of Account'), ('The codes assigned for transactions where no currency is involved', 'The codes assigned for transactions where no currency is involved'), ('Yemeni Rial', 'Yemeni Rial'), ('Rand', 'Rand'), ('Zambian Kwacha', 'Zambian Kwacha'), ('Zimbabwe Dollar', 'Zimbabwe Dollar')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_bank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_employee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_supplier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='legal_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_header',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction_header',
            name='folio_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_header',
            name='memo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_header',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='azbooks.party'),
        ),
        migrations.AlterField(
            model_name='transaction_header',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_header',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='country',
        ),
        migrations.DeleteModel(
            name='currency',
        ),
        migrations.DeleteModel(
            name='Historicalcountry',
        ),
        migrations.DeleteModel(
            name='Historicalcurrency',
        ),
    ]
