# Generated by Django 4.1.2 on 2022-10-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azbooks', '0005_alter_historicalparty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction_detail',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_detail',
            name='debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction_header',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_detail',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_detail',
            name='debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_header',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
